Table "com_transaction" {
  "id" INT(11) [pk, not null, increment]
  "commodity" VARCHAR(50) [not null]
  "created_at" DATETIME [default: NULL]
  "user_id" INT(11) [not null, default: "0"]
  "cmd" TINYINT(4) [not null, default: "0"]
  "sell_price" DOUBLE [not null, default: "0"]
  "buy_price" DOUBLE [not null, default: "0"]
  "volume" DOUBLE [not null, default: "0"]
  "prev_volume" DOUBLE [not null, default: "0"]
  "now_volume" DOUBLE [not null, default: "0"]
  "jumlah" DOUBLE [not null, default: "0"]
  "prev_wallet" DOUBLE [not null, default: "0"]
  "now_wallet" DOUBLE [not null, default: "0"]
  "confirm_at" DATETIME [not null]
  "admin_id" INT(11) [default: NULL]

Indexes {
  cmd [name: "cmd"]
  confirm_at [name: "confirm_at"]
  created_at [name: "created_at"]
  user_id [name: "user_id"]
  jumlah [name: "jumlah"]
  sell_price [name: "sell_price"]
  buy_price [name: "buy_price"]
  admin_id [name: "admin_id"]
  volume [name: "volume"]
  prev_wallet [name: "prev_wallet"]
  commodity [name: "commodity"]
  now_wallet [name: "now_wallet"]
  prev_volume [name: "prev_volume"]
  now_volume [name: "now_volume"]
}
}
