Table "users" {
  "id" INT(11) [pk, not null, increment]
  "username" VARCHAR(50) [default: NULL]
  "name" VARCHAR(50) [not null]
  "email" VARCHAR(50) [not null]
  "password" VARCHAR(75) [not null]
  "pin" VARCHAR(75) [default: NULL]
  "last_activity" DATETIME [default: NULL]
  "phone" VARCHAR(75) [default: NULL]
  "district" VARCHAR(75) [default: NULL]
  "alamat" VARCHAR(250) [default: NULL]
  "created_at" DATETIME [default: `utc_timestamp()`]
  "verify_token" VARCHAR(255) [default: NULL]
  "verify_expiry" DATETIME [default: NULL]
  "pin_token" VARCHAR(255) [default: NULL]
  "pin_expiry" DATETIME [default: NULL]
  "pass_token" VARCHAR(255) [default: NULL]
  "pass_expiry" DATETIME [default: NULL]
  "verified" TINYINT(4) [not null, default: "0"]
  "wallet" DOUBLE [not null, default: "0"]
  "emas" DOUBLE [not null, default: "0"]
  "avg_harga_beli" INT(11) [default: "0"]

Indexes {
  email [unique, name: "email"]
  username [unique, name: "username"]
  name [name: "name"]
  created_at [name: "created_at"]
  verified [name: "verified"]
  password [name: "password"]
  verify_token [name: "verify_token"]
  verify_expiry [name: "verify_expiry"]
  district [name: "district"]
  alamat [name: "alamat"]
  phone [name: "phone"]
  wallet [name: "wallet"]
  emas [name: "emas"]
}
}
