Table "withdrawal_gold" {
  "id" INT(11) [pk, not null, increment]
  "user_id" INT(11) [not null]
  "province_id" INT(11) [not null]
  "city_id" INT(11) [not null]
  "district_id" INT(11) [not null]
  "post_code" VARCHAR(50) [not null]
  "address" TEXT [not null]
  "status" INT(1) [not null, default: "0", note: '0=pending,1=verified,2=declined, 3=onprocess, 4=ondeliver, 5=done']
  "time" DATETIME [not null]
  "emas" DOUBLE [not null]
  "fee" DOUBLE [not null, default: "0"]
  "insurance" DOUBLE [not null, default: "0"]
  "delivery_name" VARCHAR(20) [not null]
  "delivery_type" VARCHAR(20) [not null]
  "delivery_fare" DOUBLE [not null]
  "delivery_estimates_days" VARCHAR(20) [not null]
  "delivery_desc" VARCHAR(75) [not null, default: ""]
  "delivery_no" VARCHAR(75) [default: NULL]
  "document" VARCHAR(255) [default: NULL]
  "cashier" INT(11) [default: NULL]
  "cashier_approval" TINYINT(4) [default: NULL]
  "cashier_approval_tm" DATETIME [default: NULL]
  "MODIFY_TIME" DATETIME [not null]
  "cashier_note" TEXT [default: NULL]
  "verify_token" VARCHAR(255) [default: NULL]
  "verify_expiry" DATETIME [default: NULL]
  "verified" TINYINT(4) [not null, default: "0"]

Indexes {
  user_id [name: "user_id"]
  verify_token [name: "verify_token"]
  verify_expiry [name: "verify_expiry"]
  verified [name: "verified"]
}
}
