CREATE TABLE `com_transaction_history` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`commodity` VARCHAR(50) NOT NULL,
	`created_at` DATETIME NULL DEFAULT NULL,
	`user_id` INT(11) NOT NULL DEFAULT '0',
	`cmd` TINYINT(4) NOT NULL DEFAULT '0',
	`sell_price` DOUBLE NOT NULL DEFAULT '0',
	`buy_price` DOUBLE NOT NULL DEFAULT '0',
	`volume` DOUBLE NOT NULL DEFAULT '0',
	`prev_volume` DOUBLE NOT NULL DEFAULT '0',
	`now_volume` DOUBLE NOT NULL DEFAULT '0',
	`jumlah` DOUBLE NOT NULL DEFAULT '0',
	`prev_wallet` DOUBLE NOT NULL DEFAULT '0',
	`now_wallet` DOUBLE NOT NULL DEFAULT '0',
	`confirm_at` DATETIME NOT NULL,
	`admin_id` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`id`),
	INDEX `cmd` (`cmd`),
	INDEX `confirm_at` (`confirm_at`),
	INDEX `created_at` (`created_at`),
	INDEX `user_id` (`user_id`),
	INDEX `jumlah` (`jumlah`),
	INDEX `sell_price` (`sell_price`),
	INDEX `buy_price` (`buy_price`),
	INDEX `admin_id` (`admin_id`),
	INDEX `volume` (`volume`),
	INDEX `prev_wallet` (`prev_wallet`),
	INDEX `commodity` (`commodity`),
	INDEX `now_wallet` (`now_wallet`),
	INDEX `prev_volume` (`prev_volume`),
	INDEX `now_volume` (`now_volume`)
)
ENGINE=InnoDB
;
