CREATE TABLE `delivery` (
	`id` INT(5) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(100) NOT NULL,
	`type` VARCHAR(100) NOT NULL,
	`fare` DOUBLE NOT NULL,
	`estimates_days` VARCHAR(200) NOT NULL,
	`active` TINYINT(5) NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
)
ENGINE=InnoDB
AUTO_INCREMENT=3
;
